// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Movies_EFCore.Data;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Movies_EFCore.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260205090630_SeedData")]
    partial class SeedData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ActorMovie", b =>
                {
                    b.Property<int>("ActorsActorId")
                        .HasColumnType("integer");

                    b.Property<int>("MoviesMovieId")
                        .HasColumnType("integer");

                    b.HasKey("ActorsActorId", "MoviesMovieId");

                    b.HasIndex("MoviesMovieId");

                    b.ToTable("ActorMovie");
                });

            modelBuilder.Entity("GenreMovie", b =>
                {
                    b.Property<int>("GenresGenreId")
                        .HasColumnType("integer");

                    b.Property<int>("MoviesMovieId")
                        .HasColumnType("integer");

                    b.HasKey("GenresGenreId", "MoviesMovieId");

                    b.HasIndex("MoviesMovieId");

                    b.ToTable("GenreMovie");
                });

            modelBuilder.Entity("Movies_EFCore.Entities.Actor", b =>
                {
                    b.Property<int>("ActorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ActorId"));

                    b.Property<int>("Age")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("ActorId");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("actors", (string)null);

                    b.HasData(
                        new
                        {
                            ActorId = 1,
                            Age = 48,
                            Name = "Leonardo DiCaprio"
                        },
                        new
                        {
                            ActorId = 2,
                            Age = 59,
                            Name = "Brad Pitt"
                        },
                        new
                        {
                            ActorId = 3,
                            Age = 85,
                            Name = "Morgan Freeman"
                        },
                        new
                        {
                            ActorId = 4,
                            Age = 38,
                            Name = "Scarlett Johansson"
                        },
                        new
                        {
                            ActorId = 5,
                            Age = 66,
                            Name = "Tom Hanks"
                        },
                        new
                        {
                            ActorId = 6,
                            Age = 73,
                            Name = "Meryl Streep"
                        },
                        new
                        {
                            ActorId = 7,
                            Age = 60,
                            Name = "Johnny Depp"
                        },
                        new
                        {
                            ActorId = 8,
                            Age = 47,
                            Name = "Angelina Jolie"
                        },
                        new
                        {
                            ActorId = 9,
                            Age = 58,
                            Name = "Robert Downey Jr."
                        },
                        new
                        {
                            ActorId = 10,
                            Age = 39,
                            Name = "Chris Hemsworth"
                        },
                        new
                        {
                            ActorId = 11,
                            Age = 42,
                            Name = "Chris Evans"
                        },
                        new
                        {
                            ActorId = 12,
                            Age = 44,
                            Name = "Chris Pratt"
                        },
                        new
                        {
                            ActorId = 13,
                            Age = 40,
                            Name = "Anne Hathaway"
                        },
                        new
                        {
                            ActorId = 14,
                            Age = 34,
                            Name = "Emma Stone"
                        },
                        new
                        {
                            ActorId = 15,
                            Age = 42,
                            Name = "Ryan Gosling"
                        },
                        new
                        {
                            ActorId = 16,
                            Age = 52,
                            Name = "Matt Damon"
                        },
                        new
                        {
                            ActorId = 17,
                            Age = 53,
                            Name = "Hugh Jackman"
                        },
                        new
                        {
                            ActorId = 18,
                            Age = 41,
                            Name = "Natalie Portman"
                        },
                        new
                        {
                            ActorId = 19,
                            Age = 57,
                            Name = "Keanu Reeves"
                        },
                        new
                        {
                            ActorId = 20,
                            Age = 51,
                            Name = "Dwayne Johnson"
                        },
                        new
                        {
                            ActorId = 21,
                            Age = 37,
                            Name = "Gal Gadot"
                        },
                        new
                        {
                            ActorId = 22,
                            Age = 26,
                            Name = "Zendaya"
                        },
                        new
                        {
                            ActorId = 23,
                            Age = 55,
                            Name = "Will Smith"
                        },
                        new
                        {
                            ActorId = 24,
                            Age = 43,
                            Name = "Chris Pine"
                        },
                        new
                        {
                            ActorId = 25,
                            Age = 32,
                            Name = "Jennifer Lawrence"
                        },
                        new
                        {
                            ActorId = 26,
                            Age = 33,
                            Name = "Margot Robbie"
                        },
                        new
                        {
                            ActorId = 27,
                            Age = 45,
                            Name = "Tom Hardy"
                        },
                        new
                        {
                            ActorId = 28,
                            Age = 77,
                            Name = "Galileo Galilei"
                        },
                        new
                        {
                            ActorId = 29,
                            Age = 53,
                            Name = "Cate Blanchett"
                        },
                        new
                        {
                            ActorId = 30,
                            Age = 65,
                            Name = "Daniel Day-Lewis"
                        });
                });

            modelBuilder.Entity("Movies_EFCore.Entities.Director", b =>
                {
                    b.Property<int>("DirectorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("DirectorId"));

                    b.Property<int>("Age")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("DirectorId");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("directors", (string)null);

                    b.HasData(
                        new
                        {
                            DirectorId = 1,
                            Age = 52,
                            Name = "Christopher Nolan"
                        },
                        new
                        {
                            DirectorId = 2,
                            Age = 76,
                            Name = "Steven Spielberg"
                        },
                        new
                        {
                            DirectorId = 3,
                            Age = 60,
                            Name = "Quentin Tarantino"
                        },
                        new
                        {
                            DirectorId = 4,
                            Age = 79,
                            Name = "Martin Scorsese"
                        },
                        new
                        {
                            DirectorId = 5,
                            Age = 68,
                            Name = "James Cameron"
                        },
                        new
                        {
                            DirectorId = 6,
                            Age = 85,
                            Name = "Ridley Scott"
                        },
                        new
                        {
                            DirectorId = 7,
                            Age = 60,
                            Name = "Peter Jackson"
                        },
                        new
                        {
                            DirectorId = 8,
                            Age = 64,
                            Name = "Tim Burton"
                        },
                        new
                        {
                            DirectorId = 9,
                            Age = 92,
                            Name = "Clint Eastwood"
                        },
                        new
                        {
                            DirectorId = 10,
                            Age = 60,
                            Name = "David Fincher"
                        },
                        new
                        {
                            DirectorId = 11,
                            Age = 53,
                            Name = "Guy Ritchie"
                        },
                        new
                        {
                            DirectorId = 12,
                            Age = 52,
                            Name = "Sofia Coppola"
                        },
                        new
                        {
                            DirectorId = 13,
                            Age = 54,
                            Name = "Wes Anderson"
                        },
                        new
                        {
                            DirectorId = 14,
                            Age = 59,
                            Name = "Guillermo del Toro"
                        },
                        new
                        {
                            DirectorId = 15,
                            Age = 52,
                            Name = "Denis Villeneuve"
                        },
                        new
                        {
                            DirectorId = 16,
                            Age = 60,
                            Name = "Alfonso Cuarón"
                        },
                        new
                        {
                            DirectorId = 17,
                            Age = 67,
                            Name = "Spike Lee"
                        },
                        new
                        {
                            DirectorId = 18,
                            Age = 46,
                            Name = "Taika Waititi"
                        },
                        new
                        {
                            DirectorId = 19,
                            Age = 44,
                            Name = "Jordan Peele"
                        },
                        new
                        {
                            DirectorId = 20,
                            Age = 57,
                            Name = "Baz Luhrmann"
                        },
                        new
                        {
                            DirectorId = 21,
                            Age = 57,
                            Name = "J.J. Abrams"
                        },
                        new
                        {
                            DirectorId = 22,
                            Age = 69,
                            Name = "Ron Howard"
                        },
                        new
                        {
                            DirectorId = 23,
                            Age = 58,
                            Name = "Michael Bay"
                        },
                        new
                        {
                            DirectorId = 24,
                            Age = 83,
                            Name = "Francis Ford Coppola"
                        },
                        new
                        {
                            DirectorId = 25,
                            Age = 67,
                            Name = "Ang Lee"
                        },
                        new
                        {
                            DirectorId = 26,
                            Age = 68,
                            Name = "Robert Zemeckis"
                        },
                        new
                        {
                            DirectorId = 27,
                            Age = 50,
                            Name = "Patty Jenkins"
                        },
                        new
                        {
                            DirectorId = 28,
                            Age = 52,
                            Name = "M. Night Shyamalan"
                        },
                        new
                        {
                            DirectorId = 29,
                            Age = 40,
                            Name = "Greta Gerwig"
                        },
                        new
                        {
                            DirectorId = 30,
                            Age = 55,
                            Name = "Christopher McQuarrie"
                        });
                });

            modelBuilder.Entity("Movies_EFCore.Entities.Genre", b =>
                {
                    b.Property<int>("GenreId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("GenreId"));

                    b.Property<string>("GenreName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("GenreId");

                    b.HasIndex("GenreName")
                        .IsUnique();

                    b.ToTable("genres", (string)null);

                    b.HasData(
                        new
                        {
                            GenreId = 1,
                            GenreName = "Action"
                        },
                        new
                        {
                            GenreId = 2,
                            GenreName = "Adventure"
                        },
                        new
                        {
                            GenreId = 3,
                            GenreName = "Comedy"
                        },
                        new
                        {
                            GenreId = 4,
                            GenreName = "Drama"
                        },
                        new
                        {
                            GenreId = 5,
                            GenreName = "Thriller"
                        },
                        new
                        {
                            GenreId = 6,
                            GenreName = "Horror"
                        },
                        new
                        {
                            GenreId = 7,
                            GenreName = "Sci-Fi"
                        },
                        new
                        {
                            GenreId = 8,
                            GenreName = "Romance"
                        },
                        new
                        {
                            GenreId = 9,
                            GenreName = "Fantasy"
                        },
                        new
                        {
                            GenreId = 10,
                            GenreName = "Crime"
                        },
                        new
                        {
                            GenreId = 11,
                            GenreName = "Mystery"
                        },
                        new
                        {
                            GenreId = 12,
                            GenreName = "Animation"
                        },
                        new
                        {
                            GenreId = 13,
                            GenreName = "Musical"
                        },
                        new
                        {
                            GenreId = 14,
                            GenreName = "Biography"
                        },
                        new
                        {
                            GenreId = 15,
                            GenreName = "War"
                        },
                        new
                        {
                            GenreId = 16,
                            GenreName = "Family"
                        },
                        new
                        {
                            GenreId = 17,
                            GenreName = "History"
                        },
                        new
                        {
                            GenreId = 18,
                            GenreName = "Sport"
                        },
                        new
                        {
                            GenreId = 19,
                            GenreName = "Western"
                        },
                        new
                        {
                            GenreId = 20,
                            GenreName = "Documentary"
                        },
                        new
                        {
                            GenreId = 21,
                            GenreName = "Musical Comedy"
                        },
                        new
                        {
                            GenreId = 22,
                            GenreName = "Psychological Thriller"
                        },
                        new
                        {
                            GenreId = 23,
                            GenreName = "Political Drama"
                        },
                        new
                        {
                            GenreId = 24,
                            GenreName = "Romantic Comedy"
                        },
                        new
                        {
                            GenreId = 25,
                            GenreName = "Epic"
                        },
                        new
                        {
                            GenreId = 26,
                            GenreName = "Satire"
                        },
                        new
                        {
                            GenreId = 27,
                            GenreName = "Cyberpunk"
                        },
                        new
                        {
                            GenreId = 28,
                            GenreName = "Dark Fantasy"
                        },
                        new
                        {
                            GenreId = 29,
                            GenreName = "Superhero"
                        },
                        new
                        {
                            GenreId = 30,
                            GenreName = "Adventure Comedy"
                        });
                });

            modelBuilder.Entity("Movies_EFCore.Entities.Movie", b =>
                {
                    b.Property<int>("MovieId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("MovieId"));

                    b.Property<int>("DirectorId")
                        .HasColumnType("integer");

                    b.Property<string>("MovieTitle")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("ReleaseYear")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(2000);

                    b.HasKey("MovieId");

                    b.HasIndex("DirectorId");

                    b.HasIndex("MovieTitle", "ReleaseYear")
                        .IsUnique();

                    b.ToTable("movies", (string)null);

                    b.HasData(
                        new
                        {
                            MovieId = 1,
                            DirectorId = 1,
                            MovieTitle = "Inception",
                            ReleaseYear = 2010
                        },
                        new
                        {
                            MovieId = 2,
                            DirectorId = 1,
                            MovieTitle = "Interstellar",
                            ReleaseYear = 2014
                        },
                        new
                        {
                            MovieId = 3,
                            DirectorId = 2,
                            MovieTitle = "Jurassic Park",
                            ReleaseYear = 1993
                        },
                        new
                        {
                            MovieId = 4,
                            DirectorId = 2,
                            MovieTitle = "E.T.",
                            ReleaseYear = 1982
                        },
                        new
                        {
                            MovieId = 5,
                            DirectorId = 3,
                            MovieTitle = "Pulp Fiction",
                            ReleaseYear = 1994
                        },
                        new
                        {
                            MovieId = 6,
                            DirectorId = 3,
                            MovieTitle = "Django Unchained",
                            ReleaseYear = 2012
                        },
                        new
                        {
                            MovieId = 7,
                            DirectorId = 4,
                            MovieTitle = "The Wolf of Wall Street",
                            ReleaseYear = 2013
                        },
                        new
                        {
                            MovieId = 8,
                            DirectorId = 5,
                            MovieTitle = "Titanic",
                            ReleaseYear = 1997
                        },
                        new
                        {
                            MovieId = 9,
                            DirectorId = 6,
                            MovieTitle = "Gladiator",
                            ReleaseYear = 2000
                        },
                        new
                        {
                            MovieId = 10,
                            DirectorId = 7,
                            MovieTitle = "The Lord of the Rings",
                            ReleaseYear = 2001
                        },
                        new
                        {
                            MovieId = 11,
                            DirectorId = 8,
                            MovieTitle = "Alice in Wonderland",
                            ReleaseYear = 2010
                        },
                        new
                        {
                            MovieId = 12,
                            DirectorId = 9,
                            MovieTitle = "Gran Torino",
                            ReleaseYear = 2008
                        },
                        new
                        {
                            MovieId = 13,
                            DirectorId = 10,
                            MovieTitle = "Fight Club",
                            ReleaseYear = 1999
                        },
                        new
                        {
                            MovieId = 14,
                            DirectorId = 11,
                            MovieTitle = "Sherlock Holmes",
                            ReleaseYear = 2009
                        },
                        new
                        {
                            MovieId = 15,
                            DirectorId = 12,
                            MovieTitle = "Lost in Translation",
                            ReleaseYear = 2003
                        },
                        new
                        {
                            MovieId = 16,
                            DirectorId = 13,
                            MovieTitle = "The Grand Budapest Hotel",
                            ReleaseYear = 2014
                        },
                        new
                        {
                            MovieId = 17,
                            DirectorId = 14,
                            MovieTitle = "Pan's Labyrinth",
                            ReleaseYear = 2006
                        },
                        new
                        {
                            MovieId = 18,
                            DirectorId = 15,
                            MovieTitle = "Arrival",
                            ReleaseYear = 2016
                        },
                        new
                        {
                            MovieId = 19,
                            DirectorId = 16,
                            MovieTitle = "Gravity",
                            ReleaseYear = 2013
                        },
                        new
                        {
                            MovieId = 20,
                            DirectorId = 17,
                            MovieTitle = "BlackKklansman",
                            ReleaseYear = 2018
                        },
                        new
                        {
                            MovieId = 21,
                            DirectorId = 18,
                            MovieTitle = "Jojo Rabbit",
                            ReleaseYear = 2019
                        },
                        new
                        {
                            MovieId = 22,
                            DirectorId = 19,
                            MovieTitle = "Get Out",
                            ReleaseYear = 2017
                        },
                        new
                        {
                            MovieId = 23,
                            DirectorId = 20,
                            MovieTitle = "Moulin Rouge!",
                            ReleaseYear = 2001
                        },
                        new
                        {
                            MovieId = 24,
                            DirectorId = 21,
                            MovieTitle = "Star Wars: The Force Awakens",
                            ReleaseYear = 2015
                        },
                        new
                        {
                            MovieId = 25,
                            DirectorId = 22,
                            MovieTitle = "A Beautiful Mind",
                            ReleaseYear = 2001
                        },
                        new
                        {
                            MovieId = 26,
                            DirectorId = 23,
                            MovieTitle = "Transformers",
                            ReleaseYear = 2007
                        },
                        new
                        {
                            MovieId = 27,
                            DirectorId = 24,
                            MovieTitle = "The Godfather",
                            ReleaseYear = 1972
                        },
                        new
                        {
                            MovieId = 28,
                            DirectorId = 25,
                            MovieTitle = "Life of Pi",
                            ReleaseYear = 2012
                        },
                        new
                        {
                            MovieId = 29,
                            DirectorId = 26,
                            MovieTitle = "Forrest Gump",
                            ReleaseYear = 1994
                        },
                        new
                        {
                            MovieId = 30,
                            DirectorId = 27,
                            MovieTitle = "Wonder Woman",
                            ReleaseYear = 2017
                        });
                });

            modelBuilder.Entity("ActorMovie", b =>
                {
                    b.HasOne("Movies_EFCore.Entities.Actor", null)
                        .WithMany()
                        .HasForeignKey("ActorsActorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Movies_EFCore.Entities.Movie", null)
                        .WithMany()
                        .HasForeignKey("MoviesMovieId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("GenreMovie", b =>
                {
                    b.HasOne("Movies_EFCore.Entities.Genre", null)
                        .WithMany()
                        .HasForeignKey("GenresGenreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Movies_EFCore.Entities.Movie", null)
                        .WithMany()
                        .HasForeignKey("MoviesMovieId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Movies_EFCore.Entities.Movie", b =>
                {
                    b.HasOne("Movies_EFCore.Entities.Director", "Director")
                        .WithMany("Movies")
                        .HasForeignKey("DirectorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Director");
                });

            modelBuilder.Entity("Movies_EFCore.Entities.Director", b =>
                {
                    b.Navigation("Movies");
                });
#pragma warning restore 612, 618
        }
    }
}
